import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#dbe1ff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#632892',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'on-background': '#191c1e',
        outline: '#737686',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#131b2e',
        'tertiary-container': '#656d84',
        error: '#ba1a1a',
        'surface-variant': '#e0e3e5',
        tertiary: '#4d556b',
        'surface-container': '#eceef0',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-surface': '#191c1e',
        'secondary-container': '#cb8ffd',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#e0b6ff',
        'on-primary-container': '#eeefff',
        'on-secondary-fixed': '#2d004f',
        'on-primary-fixed-variant': '#003ea8',
        'primary-container': '#2563eb',
        'secondary-fixed': '#f2daff',
        'on-error-container': '#93000a',
        surface: '#f7f9fb',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed-variant': '#3f465c',
        'on-secondary-container': '#581d87',
        'inverse-on-surface': '#eff1f3',
        'on-primary-fixed': '#00174b',
        'on-surface-variant': '#434655',
        'tertiary-fixed-dim': '#bec6e0',
        'surface-bright': '#f7f9fb',
        background: '#f7f9fb',
        'tertiary-fixed': '#dae2fd',
        'outline-variant': '#c3c6d7',
        'surface-container-low': '#f2f4f6',
        'on-tertiary-container': '#eef0ff',
        'surface-tint': '#0053db',
        'surface-dim': '#d8dadc',
        'surface-container-high': '#e6e8ea',
        primary: 'var(--primary)',
        'primary-fixed-dim': '#b4c5ff',
        secondary: 'var(--secondary)',
        'inverse-primary': '#b4c5ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        lg: '24px',
        'max-width': '1280px',
        xs: '4px',
        gutter: '24px',
        base: '4px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        sm: '8px',
        md: '16px',
      },
      fontFamily: {
        'display-lg-mobile': ['Lora', 'Georgia', 'serif'],
        'headline-sm': ['Lora', 'Georgia', 'serif'],
        'headline-md': ['Lora', 'Georgia', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Lora', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
